# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the portable Windows bundle.

Produces a onedir tree the user unzips and runs by double-clicking
``pyALDIC.exe`` -- no installer, no Python, no admin rights.

Build with ``python tools/build_exe.py`` (which pins the output paths away from
``dist/``, the directory the PyPI workflow publishes from).

The two things most likely to go wrong here are silent, so both are asserted
at build time rather than discovered by a user:

* the ``al_dic/`` prefix on every ``datas`` destination. A frozen package's
  ``__file__`` is ``sys._MEIPASS/al_dic/<subpkg>/__init__.py``, so the data
  directories the code resolves with ``Path(__file__).parent / ...`` only line
  up if the destination mirrors the package path. Get it wrong and the app
  still starts -- with seven of eight languages gone, blank spin-box arrows
  and no window icon.
* the presence of the compiled ``.qm`` catalogs, which are build products.
"""

import glob
import os
import sys

from PyInstaller.utils.hooks import copy_metadata

# --------------------------------------------------------------------------
# Preconditions
# --------------------------------------------------------------------------
SRC = os.path.join(SPECPATH, os.pardir, "src")
PKG = os.path.join(SRC, "al_dic")

# 'en' is absent by design: LanguageManager short-circuits it to the source
# strings rather than loading a catalog.
LOCALES = ("de", "es", "fr", "ja", "ko", "zh_CN", "zh_TW")
for _lc in LOCALES:
    _qm = os.path.join(PKG, "i18n", "compiled", f"al_dic_{_lc}.qm")
    assert os.path.isfile(_qm), (
        f"missing translation catalog {_qm}\n"
        "run: python tools/i18n.py compile"
    )

_arrows = glob.glob(os.path.join(PKG, "gui", "arrows", "*.svg"))
assert len(_arrows) == 4, f"expected 4 spin-box arrow SVGs, found {len(_arrows)}"

for _ic in ("pyALDIC.ico", "pyALDIC-256.png", "pyALDIC.svg"):
    assert os.path.isfile(os.path.join(PKG, "gui", "assets", "icon", _ic)), _ic

ICON = os.path.join(PKG, "gui", "assets", "icon", "pyALDIC.ico")

# --------------------------------------------------------------------------
# Version resource (Explorer properties / SmartScreen reputation)
# --------------------------------------------------------------------------
_ver_ns = {}
with open(os.path.join(PKG, "__init__.py"), encoding="utf-8") as _f:
    for _line in _f:
        if _line.startswith("__version__"):
            exec(_line, _ver_ns)
            break
VERSION = _ver_ns["__version__"]
_v = tuple(int(p) for p in VERSION.split(".")[:3]) + (0,)

VERSION_FILE = os.path.join(SPECPATH, "version_info.txt")
with open(VERSION_FILE, "w", encoding="utf-8") as _f:
    _f.write(f"""# Generated by pyaldic.spec -- do not edit, do not commit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={_v}, prodvers={_v}, mask=0x3f, flags=0x0,
                    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('CompanyName', 'Zixiang (Zach) Tong'),
        StringStruct('FileDescription', 'pyALDIC - Augmented Lagrangian Digital Image Correlation'),
        StringStruct('FileVersion', '{VERSION}'),
        StringStruct('InternalName', 'pyALDIC'),
        StringStruct('LegalCopyright', 'BSD-3-Clause'),
        StringStruct('OriginalFilename', 'pyALDIC.exe'),
        StringStruct('ProductName', 'pyALDIC'),
        StringStruct('ProductVersion', '{VERSION}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""")

# --------------------------------------------------------------------------
# Bundle contents
# --------------------------------------------------------------------------
datas = [
    # The 'al_dic/' destination prefix is load-bearing -- see the module
    # docstring. Each of these is resolved at runtime with
    # Path(__file__).parent, in i18n/__init__.py, gui/theme.py and gui/icons.py.
    (os.path.join(PKG, "i18n", "compiled", "*.qm"), "al_dic/i18n/compiled"),
    (os.path.join(PKG, "gui", "arrows", "*.svg"), "al_dic/gui/arrows"),
    (os.path.join(PKG, "gui", "assets", "icon", "*"), "al_dic/gui/assets/icon"),
]

# imageio/__init__.py calls importlib.metadata.version("imageio") at import
# time, which raises PackageNotFoundError unless the .dist-info comes along.
datas += copy_metadata("imageio")

hiddenimports = [
    # Imported behind try/except in gui/icons.py. Losing it does not raise --
    # every toolbar icon silently becomes an empty QIcon.
    "PySide6.QtSvg",

    # Numba picks a threading backend by trying these in order, with
    # function-level imports the module graph cannot see. tbbpool is
    # deliberately absent: TBB is not a dependency of this project, the
    # environment does not provide tbb12.dll, and listing it made PyInstaller
    # satisfy the dependency from Anaconda's base environment -- which then won
    # the layer selection, so the bundle ran on a thread pool the developers
    # never tested and no user could have. omp (vcomp140.dll, bundled above) is
    # the intended layer; workqueue is the fallback.
    "numba.np.ufunc.omppool",
    "numba.np.ufunc.workqueue",
    "numba.np.ufunc._internal",
    "numba.np.ufunc._num_threads",

    # Named only as the string "Agg" in export/colorbar.py.
    "matplotlib.backends.backend_agg",

    # GIF export resolves the "GIF" plugin string to this at runtime.
    "imageio.plugins.pillow",
    "PIL.Image",
    "PIL.GifImagePlugin",
]

binaries = []

# OpenCV's FFmpeg backend. hook-cv2 collects cv2's DLLs, but the filename
# embeds the OpenCV version (4.13 -> ...ffmpeg4130_64.dll, 5.0 ->
# ...ffmpeg500_64.dll), so glob rather than hardcode. Without it every video
# export fails: both the mp4v path and the XVID/.avi fallback refuse to open.
try:
    import cv2 as _cv2

    for _dll in glob.glob(
        os.path.join(os.path.dirname(_cv2.__file__), "opencv_videoio_ffmpeg*.dll")
    ):
        binaries.append((_dll, "cv2"))
except ImportError:  # pragma: no cover
    pass

# The OpenMP runtime backing numba's 'omp' threading layer. It resolves from
# System32 (the VC++ redistributable), which PyInstaller excludes from
# collection by design -- so on a machine without the redistributable,
# omppool fails to import and numba drops to 'workqueue' without saying so.
# App-local deployment of this DLL is permitted by the redistributable licence.
_vcomp = os.path.join(
    os.environ.get("SystemRoot", r"C:\Windows"), "System32", "vcomp140.dll"
)
if os.path.isfile(_vcomp):
    binaries.append((_vcomp, "."))

excludes = [
    # --- Qt modules the application does not import ----------------------
    # Kept: QtCore, QtGui, QtWidgets, QtSvg. These are insurance rather than a
    # saving: PyInstaller's Qt hooks are per-module, so on a correct build the
    # heavy ones are already absent. They stop a stray collect_all('PySide6')
    # from doubling the bundle.
    "PySide6.Qt3DAnimation", "PySide6.Qt3DCore", "PySide6.Qt3DExtras",
    "PySide6.Qt3DInput", "PySide6.Qt3DLogic", "PySide6.Qt3DRender",
    "PySide6.QtAxContainer", "PySide6.QtBluetooth", "PySide6.QtCharts",
    "PySide6.QtConcurrent", "PySide6.QtDataVisualization", "PySide6.QtDBus",
    "PySide6.QtDesigner", "PySide6.QtGraphs", "PySide6.QtGraphsWidgets",
    "PySide6.QtHelp", "PySide6.QtHttpServer", "PySide6.QtLocation",
    "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets",
    "PySide6.QtNetworkAuth", "PySide6.QtNfc", "PySide6.QtOpenGL",
    "PySide6.QtOpenGLWidgets", "PySide6.QtPdf", "PySide6.QtPdfWidgets",
    "PySide6.QtPositioning", "PySide6.QtQml", "PySide6.QtQuick",
    "PySide6.QtQuick3D", "PySide6.QtQuickControls2", "PySide6.QtQuickTest",
    "PySide6.QtQuickWidgets", "PySide6.QtRemoteObjects", "PySide6.QtScxml",
    "PySide6.QtSensors", "PySide6.QtSerialBus", "PySide6.QtSerialPort",
    "PySide6.QtSpatialAudio", "PySide6.QtSql", "PySide6.QtStateMachine",
    "PySide6.QtSvgWidgets", "PySide6.QtTest", "PySide6.QtTextToSpeech",
    "PySide6.QtUiTools", "PySide6.QtWebChannel", "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineQuick", "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebSockets", "PySide6.QtWebView", "PySide6.QtXml",

    # QtNetwork and QtPrintSupport are deliberately NOT excluded: neither is
    # imported, so neither is collected, and excluding a module Qt might pull
    # internally trades a guaranteed crash for a saving of zero bytes.

    # Rival Qt bindings must never co-exist in one bundle.
    "PyQt5", "PyQt6", "PySide2", "shiboken2",

    # Declared in pyproject.toml but imported nowhere in src/, tests/, tools/
    # or examples/. Excluding it keeps a future stray import from dragging in
    # 25 MB plus scikit-image's seventeen collect-everything hooks.
    "skimage",

    # imageio plugins that are unreachable: only "GIF" (-> pillow) is used.
    # imageio_ffmpeg would otherwise add a ~87 MB ffmpeg.exe.
    "imageio_ffmpeg", "imageio.plugins.ffmpeg", "imageio.plugins.pyav",
    "imageio.plugins.freeimage", "imageio.plugins.gdal",
    "imageio.plugins.rawpy", "imageio.plugins.simpleitk",
    "imageio.plugins.dicom", "imageio.plugins.fits",

    # No matplotlib canvas is embedded; rendering goes through Agg.
    "matplotlib.backends.backend_qtagg",
    "matplotlib.backends.backend_qtcairo",
    "matplotlib.backends.backend_webagg",
    "matplotlib.backends.backend_tkagg",

    # Never imported by the application.
    "tkinter", "IPython", "jupyter", "notebook", "pytest", "hypothesis",
    "sphinx", "pandas", "setuptools", "pip",
]

# --------------------------------------------------------------------------
# Ambient-DLL guard
# --------------------------------------------------------------------------
# PyInstaller resolves a binary dependency by searching PATH, so any DLL the
# build machine happens to have can end up in the bundle and shadow the one
# the target machine would have used. That is not hypothetical: it broke the
# first build of this spec outright.
#
# PySide6's Qt6Core.dll is built against the ICU that ships in Windows'
# System32, which exports UNVERSIONED symbols (ucnv_open). A standard ICU
# build -- Anaconda's, for one -- exports VERSIONED symbols (ucnv_open_73) and
# nothing else. Collecting the latter into the bundle root shadowed System32's
# copy, so Qt6Core could not resolve ucnv_open and every PySide6 import died
# with "DLL load failed ... The specified procedure could not be found". The
# application never got a window; nothing was logged; nothing named ICU.
#
# Windows 10 1703 and later always provide System32's ICU, so dropping these
# is safe as well as necessary.
# Must resolve from Windows, never from the bundle.
AMBIENT_DENY = ("icuuc", "icuin", "icudt", "icuio")

# Dead weight that decides behaviour if it is allowed to load. numba ships
# tbbpool.pyd inside its package, so PyInstaller collects it as an ordinary
# binary whatever hiddenimports says, and tbbpool.pyd imports tbb12.dll. This
# environment has no tbb12.dll -- `from numba.np.ufunc import tbbpool` raises
# ImportError here -- so PyInstaller satisfied it from Anaconda's base
# installation instead. The bundle then selected 'tbb' as its threading layer:
# a thread pool nobody had tested, that no user of the wheel would ever get.
# Dropping the extension leaves 'omp' (vcomp140.dll, bundled above) with
# 'workqueue' behind it, which is what the source install uses.
DEAD_EXTENSIONS = ("tbbpool", "tbb12")

# Sourced from outside the environment on purpose: see the vcomp140 note above.
AMBIENT_ALLOW = {"vcomp140.dll"}


def _drop_ambient(binaries):
    """Remove DLLs that must resolve from the OS, and report the rest."""
    kept, dropped = [], []
    for entry in binaries:
        name = os.path.basename(entry[0]).lower()
        unwanted = name.startswith(AMBIENT_DENY) or name.startswith(DEAD_EXTENSIONS)
        (dropped if unwanted else kept).append(entry)
    for entry in dropped:
        print(f"spec: dropping {entry[0]} <- {entry[1]}")

    # Anything else sourced from outside the build environment is the same
    # class of hazard, and it has already produced two distinct silent
    # breakages here (Anaconda's ICU, Anaconda's libexpat). Fail the build
    # rather than ship it. sys.base_prefix covers a venv, whose stdlib
    # extension DLLs live in the base installation.
    roots = {os.path.normcase(sys.prefix), os.path.normcase(sys.base_prefix)}
    strays = []
    for entry in kept:
        src = os.path.normcase(str(entry[1] or ""))
        if not src or os.path.basename(src) in AMBIENT_ALLOW:
            continue
        if not any(src.startswith(root) for root in roots):
            strays.append((entry[0], entry[1]))

    if strays and not os.environ.get("PYALDIC_ALLOW_AMBIENT"):
        listing = "\n".join(f"    {dest}  <-  {src}" for dest, src in strays)
        raise SystemExit(
            "\nspec: refusing to build -- these binaries were resolved from "
            "outside the build environment\n"
            f"      ({sys.prefix}):\n{listing}\n\n"
            "      A DLL picked up from the build machine's PATH shadows the "
            "one the\n"
            "      target machine would load, and the failure is silent: the "
            "bundle\n"
            "      builds, starts, and loses a feature. Build in a clean venv, "
            "or run\n"
            "      tools/build_exe.py, which puts the environment's own DLL "
            "directories\n"
            "      first. Set PYALDIC_ALLOW_AMBIENT=1 to override deliberately."
        )
    return kept


a = Analysis(
    [os.path.join(SPECPATH, "pyaldic_launcher.py")],
    pathex=[SRC],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[os.path.join(SPECPATH, "rthook_pyaldic.py")],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)

a.binaries = _drop_ambient(a.binaries)

pyz = PYZ(a.pure)

# UPX stays off: compressing Qt's DLLs is a dependable source of antivirus
# false positives and load failures, and this bundle is already unsigned.
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="pyALDIC",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    icon=ICON,
    version=VERSION_FILE,
)

# A console twin sharing the same Analysis. Costs ~1 MB of bootloader and buys
# a stdout: somewhere for CI to read a self-test result, and somewhere for a
# user to see a traceback when the windowed build refuses to start.
exe_console = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="pyALDIC-console",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    icon=ICON,
    version=VERSION_FILE,
)

coll = COLLECT(
    exe,
    exe_console,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="pyALDIC",
)
